### ISSUE TITLE
feedback vizitka

### ISSUE THREAD

**Issue by jirkasemmler** [KaterinaHajnova/PROJEKT-Vizitka#1]
- [x] grafické chyby ![image](https://user-images.githubusercontent.com/13363655/110250600-66a9ac00-7f7c-11eb-9b1a-aecd9cd6929b.png)
- [x] https://github.com/KaterinaHajnova/PROJEKT-Vizitka/blob/9de044e46ee68406011fc3a292987f0e36103be6/style.css#L14 bude všechen text na celém webu vždy jen justify? (řečnická otázka - odpověd je "asi ne", takže bys to neměla takto globálně nastavovat)
- [x] https://github.com/KaterinaHajnova/PROJEKT-Vizitka/blob/9de044e46ee68406011fc3a292987f0e36103be6/style.css#L39 tady je lepší right: -75px. Protože je lepší to udělat relativní k tomu pravému hornímu rohu. Kdyby ten bílý box změnil velikost (tady zejména šířka), tak by eliška už nebyla na svém místě. Když to bude pozicované top: -75px; right: -75px; tak bude Eliška pořád správně "v rohu
- [x]  a neposouvat to přes margin ale přes top/left/right/bottom. Absolutní pozici tam máš správně.
- [x] https://github.com/KaterinaHajnova/PROJEKT-Vizitka/blob/9de044e46ee68406011fc3a292987f0e36103be6/style.css#L52 v twitter i facebook nastavuješ stejný základ. Lepší by bylo mít 1 třídu kde se nastaví základ a pak ve facebook/twitter nastavit jen barvu

**Comment by KaterinaHajnova** [comment]
Zmeny zapracovany a pushnuty do gitu. Mely by byt ted uz videt. 
Diky moc za feedback.
